statsdtest:
  container_name: kolektor
  hostname: kolektor
  ports:
    - "10001:10001/udp"
  volumes:
    - /Users/evanpease/work:/opt/go
  image: ubuntu:latest
  command: /bin/sh -c "while true; do /bin/echo 'hello'; sleep 100; done;"
